# Generated by Django 3.1.4 on 2020-12-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201209_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='City',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='State',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
